### PR TITLE
missing Nov release interactivity

### PR DESCRIPTION
**Pull request by shengyaliu1212**
Hi @nbarras79 and @mthaddeusm ,

I'm seeing some errors in our new localization release today, and I realized that my delivery last time to you missed a big chunk of the translations - my apologies! Please take a look and import these files when you're available. Once you're done please merge the Pull Request so we will have a clean delivery next time ;)

Thanks!!

### CODE REVIEW

**Comment by mthaddeusm** [comment]
Hi Cissy,
I will jump on these tomorrow. I am having a hard time figuring out how to
read this email from GitHub. Can you help me figure out what needs to be
done. Maybe we need a GitHub training session.
Thanks,
Matt

*Matt Miele*
Trailhead Interactivity Program Manager/Instructional Designer | Salesforce
978-476-9449

**Comment by shengyaliu1212** [comment]
Hi @mthaddeusm ,

Do you have updates on this? No rush but just would like to manage Japan's expectations. (BTW, you can click the "View it in Github" link at the bottom of your email to see our conversation in GitHub.) Thanks!!!

**Comment by mthaddeusm** [comment]
HI Cissy,
I am still having a hard time deciphering what needs to be done here. Can
you help me translate the need?  (No pun intended.)
Thanks!

*Matt Miele*
Trailhead Interactivity Program Manager/Instructional Designer | Salesforce
978-476-9449

**Comment by shengyaliu1212** [comment]
Hi @mthaddeusm ,

the files in this PR need to be imported to production. Currently, these interactivities are broken - does that help? Thanks!

**Pull request merged**
